export const COLLECTIONS = {
    cities: "cities",
    users: "users",
    aadhaarIdentityVault: "aadhaar_identity_vault",
    properties: "properties",
    rooms: "rooms",
    beds: "beds",
    bedBlocks: "bed_blocks",
    bedLocks: "bed_locks",
    bedIssueReports: "bed_issue_reports",
    bookingAvailability: "booking_availability",
    bookings: "bookings",
    payments: "payments",
    ownerPayouts: "owner_payouts",
    auditLogs: "audit_logs",
    ownerApplications: "owner_applications",
    platformSettings: "platform_settings",
    demandWatchlist: "demand_watchlist",
    demandPricing: "demand_pricing",
    demandOverrides: "demand_overrides",
    ownerNotices: "owner_notices",
    ownerCommissionDues: "owner_commission_dues",
    operatorNotices: "operator_notices",
};
